config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#index'
  resources :posts
  resources :categories
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post
end

app/models/form.rb
class Form < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    has_many_attached :images
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new 
        @category = Category.new
        @categories = Category.all
    end

    def create 
        @post = Category.new category_params
        @post.save!
        redirect_to new_category_path 
    end 

    private 
    def category_params
      params.require(:category).permit(:name,:description,:kind)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        logo = Category.find_by(name: 'logo_nuevo')
        @logo = Post.find_by(category_id: logo.id)
        @posts = Post.all
        inicio = Category.find_by(name: 'inicio')
        @first = Post.find_by(category_id: inicio.id)
        @categories = Category.all
        finde = Category.find_by(name: 'vision')
        @about = Post.find_by(category_id: finde.id)
    end 

    def show
        logo = Category.find_by(name: 'logo_nuevo')
        @logo = Post.find_by(category_id: logo.id)
        @post = Post.find(params[:id])
        respond_to do |format|
            format.html
            format.json
        end
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all         
    end

    def new 
        @posts = Post.all     
        @post = Post.new
    end 

    def edit
        @post = Post.find params[:id]
    end

    def update

    end

    def create 
        @post = Post.new post_params
        @post.save!
        redirect_to posts_path 
    end 

    def destroy
        Post.destroy(params[:id])
        redirect_to posts_path 
    end
    
    private 
    def post_params
      params.require(:post).permit(:title,:comment,:date,{images:[]}, :category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/new.html.haml
.col-10.text-left.mt-3
  %h4 Gestionar Categorias
  .card
    .card-body
      = form_with  model: @category do |c|
        .row
          .col-2
            = c.label :nombre
          .col-10
            = c.text_field :name, class: "form-control"
          .col-2
            = c.label :Descripcion
          .col-10
            = c.text_area :description,  class: "form-control"
          .col-2 
            = c.label :Ubicacion
          .col-10 
            = c.text_field :kind,  class: "form-control"
          .col-2
            =c.submit "Guargar", class: "btn btn-secondary button_color_pink"
.col-10.text-left.mt-3
  .card
    .card-header
      Items Galeria
    .card-body.text-left
      - @categories.each do |post|  
        .row.mt-3.border-top.p-4
          .col-sm-2
            = post.name
            -# = image_tag url_for(image.image), alt: '', height: '80%', width: '80%', class: 'image_thumbnail'  
          .col-sm-6
            = post.description
          .col-sm-2
            = link_to('Edit', edit_post_path(post))
          .col-sm-2
            = link_to('eliminar', posts_path(@post) , method: :delete, data: { confirm: 'Estas Seguro?' })


              

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Trama Arquitectos
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins|Raleway&display=swap" rel="stylesheet">

  %body
    .d-flex#wrapper.long-sidebar
      - if controller_name != 'pages' 
        .bg-light.border-right#sidebar-wrapper
          .sidebar-heading
            Dashboard
          .list-group.list-group-flush
            = link_to "Galeria",new_post_path, class: "list-group-item list-group-item-action bg-light"
            = link_to "Categorias",new_category_path , class: "list-group-item list-group-item-action bg-light"
            = link_to "Salir","#", class: "list-group-item list-group-item-action bg-light"
            
      - if controller_name == 'posts'
        #page-content-wrapper.col-10
          .container-fluid
            %h1.mt-4
            - if notice
              %p.alert.alert-success
                = notice
            - if alert
              %p.alert.alert-danger
                = alert
            = yield
      - else 
        #page-content-wrapper.col-12.text-center
          .container-fluid
            %h1.mt-4
            - if notice
              %p.alert.alert-success
                = notice
            - if alert
              %p.alert.alert-danger
                = alert
            = yield
    

app/views/layouts/pages.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AC
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    <meta name="viewport" content="width=device-width, initial-scale=1">
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins|Raleway&display=swap" rel="stylesheet">

  %body
    .d-flex#wrapper.long-sidebar
      - if controller_name != 'pages' 
        .bg-light.border-right#sidebar-wrapper
          .sidebar-heading
            Dashboard
          .list-group.list-group-flush
            = link_to "Galeria",new_post_path, class: "list-group-item list-group-item-action bg-light"
            = link_to "Categorias",new_category_path , class: "list-group-item list-group-item-action bg-light"
            = link_to "Salir","#", class: "list-group-item list-group-item-action bg-light"
            
      - if controller_name == 'posts'
        #page-content-wrapper.col-10
          .container-fluid
            %h1.mt-4
            - if notice
              %p.alert.alert-success
                = notice
            - if alert
              %p.alert.alert-danger
                = alert
            = yield
      - else 
        #page-content-wrapper.col-12.text-center
          .container-fluid.no-gutters
            %h1.mt-4
            - if notice
              %p.alert.alert-success
                = notice
            - if alert
              %p.alert.alert-danger
                = alert
            = yield
    

app/views/pages/index.html.haml
#fm-nav
  %nav.navbar.navbar-expand-sm.fixed-top.border-bottom.bg-white
    %a{class: "navbar-brand pl-2"}
      %img.w-25.d-inline_block.align-block.float-left{src: url_for(@logo.images.first)}
    <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    -# = image_tag '', url: 'http://localhost:3000/' , class:'d-inline_block align-block'
    .collapse.navbar-collapse#navbarSupportedContent.align-items-end.flex-column
      .navbar-nav
        .nav-item
          %a.nav-link.nav-item{:href => "#Inicio"} Inicio
        .nav-item
          %a.nav-link.nav-item{:href => "#galeria"} Galeria
        .nav-item
          %a.nav-link.nav-item{:href => "#vision"} Vision
        .nav-item
          %a.nav-link.nav-item{:href => "#nosotros"} Nosotros
        .nav-item
          %a.nav-link.nav-item{:href => "#contactanos"} Contactanos  
      -# .nav-item
      -#   - if current_user
      -#     %a.nav-link{"data-toggle"=>:dropdown}
      -#       = current_user.profile.name.capitalize
      -#       = current_user.profile.last_name.capitalize
      -#     .dropdown-menu.dropdown-menu-right
      -#       .dropdown-item
      -#         = link_to "perfil", new_user_session_path, method: "delete"
      -#       .dropdown-item
      -#         = link_to "logout", destroy_user_session_path, method: "delete"
      -#   - else
      -#     .nav-item
      -#       %a.nav-link{:href => "users/sign_up"} Registrate
.section
  #inicio
    #carouselExampleControls.carousel.slide{"data-ride"=>"carousel"}
      .carousel-inner
        -@first.images.each_with_index do |image,index|
          -if image 
            -if index == 0 
              .hero
                Novum Construcciones
              .carousel-item.active.m-0.p-0
                %img.w-100.d-block{src: url_for(image)}  
            -else
              .hero
                Novum Construcciones
              .carousel-item.m-0.p-0
                %img.w.100.d-block{src: url_for(image)}
.section 
  #galeria
  .row.mt-5.pt-5
    .col-12.d-flex.justify-content-center.pb-3
      - @categories.each do |category|
        -if category.name != "test" && category.name != "about" && category.name != "vision" && category.name != "inicio"&& category.name != "logo" && category.name != "Logo" && category.name != "logo_nuevo" 
          %button.mx-0.btn.btn-default.border-right.border_secondary.button_transparent_background.filter-button{'data-filter': category.name}=category.name    
    
    - @posts.each do |post| 
      -if Category.find(post.category_id).name != "test" && Category.find(post.category_id).name != "about" && Category.find(post.category_id).name != "vision" && Category.find(post.category_id).name != "inicio"&& Category.find(post.category_id).name != "logo" && Category.find(post.category_id).name != "Logo" && Category.find(post.category_id).name != "logo_nuevo" 
        #st{class:"#{Category.find(post.category_id).name} gallery_product filter col-6 col-lg-3"}
          .img-opacity-transition
            %a.title_width.title_margin_center{href: "/pages/#{post.id}"}=post.title
            %img.img-responsive.border-0.img-thumbnail{src: url_for(post.images.first)}


.section.mt-5
  #vision
  .row.mt-5
    .col-12.col-sm-6.text-left.mt-5
      %h2=@about.title
      %p=@about.comment.html_safe
    .col-12.col-sm-6
      %img.w-10.img-responsive.img-thumbnail.w-75{src: url_for(@about.images.first)}

.section.my-5
  #nosotros
  %h1 Nosotros
  .row.mt-5
    .col-12.col-sm-4.my-5
      .card
        .card-title
          .mt-5.mb-0 
            %h2 Construccion
        .card-body
          Ejecutamos las ideas ya convertidas en proyecto con un equipo especializado y calificado en las distintas materialidades. El mandante participa desde los primeros trazos en el terreno y en todo el proceso de ejecución, lo que permite la plena satisfacción en la conclusión de la obra.
    .col-12.col-sm-4.my-5
      .card
        .card-title
          .mt-5.mb-0 
            %h2 Técnica
        .card-body
          Novum Construcciones, cuenta con un área de profesionales que se encarga de manera personalizada de los distintos trámites inconclusos o nuevos trámites, como por ejemplo: Permisos de edificación, de obras nuevas o ampliaciones catalogadas como obra menor. Regularización de viviendas que no cuenten con Recepción Final Definitiva. Patentes comerciales y cambios de destinos
    .col-12.col-sm-4.my-5
      .card
        .card-title
          .mt-5.mb-0 
            %h2 Diseño Interiores
        .card-body
          Intervenimos el espacio ya habitado mejorando la calidad del estar, asesoramos en la nueva distribución de los espacios, la luz, el color, la materia y las nuevas formas como conclusión de un estudio integrado a las ideas solicitadas por la o el mandante. 

.section.my-5
  #contactanos
  %h1 Contáctanos
  .col-12.mt-5.px-0.pt-5
    .row.mx-0.px-0.mt-5
      .col-sm-4.text-left.mb-3
        .col-12.my-3
          .row
            .col-3
              <i class="fa fa-envelope-open" style="color: grey; font-size: 40px"></i> 
            .col-9
              %h4 Email
              tramarquitectos@gmail.com
        .col-12.mt-3
          .row
            .col-3
              <i class="fa fa-address-card" style="color:grey; font-size: 40px"></i>
            .col-9
              %h4 Dirección
              Av.La Palmilla 3723 con Teniente Yavar, Santiago Región Metropolitana
        .col-12.mt-3
          .row
            .col-3
              <i class="fa fa-phone-square" style="color:grey; font-size: 40px"></i>
            .col-9
              %h4 Fono
              +56955555555
      .col-12.col-sm-8.px-0
        = form_for Page.new do |f|
          .col-12.px-0
            .row
              .col-6.py-2
                = f.text_field :name, class: "form-control", placeholder: "nombre"
              .col-6.py-2
                = f.text_field :last_name, class: "form-control", placeholder: "apellido"
              .col-12.py-2
                = f.text_field :email, class: "form-control", placeholder: "email"
              .col-12.py-2
                = f.text_area :detail, class: "form-control" , placeholder:"requerimiento", size: "5x5"
              .col-12.text-right.py-2
                = f.submit :enviar, class: "btn btn-success"
.col-12.my-3.border-top
  .col-4.my-3.mb-2.offset-4
    footer

app/views/pages/show.html.haml
#fm-nav
  %nav.navbar.navbar-expand-sm.bg-light.d-flex.justify-content-between.fixed-top
    %a{class: "navbar-brand"}
      %img.w-25.d-inline_block.align-block.float-left{src: url_for(@logo.images.first)}
      -# = image_tag '', url: 'http://localhost:3000/' , class:'d-inline_block align-block'
    .navbar-nav
      .nav-item
        %a.nav-link.nav-item{:href => "#galeria"} Galeria
      .nav-item
        %a.nav-link.nav-item{:href => "#vision"} Vision
      .nav-item
        %a.nav-link.nav-item{:href => "#nosotros"} Nosotros
      .nav-item
        %a.nav-link.nav-item{:href => "#nosotros"} Contactanos  
.col-12.mt-5.pt-5
  .row
    .col-6 
      #carouselExampleControls.carousel.slide{"data-ride"=>"carousel"}
        .carousel-inner
          -@post.images.each_with_index do |image,index|
            -if index == 0 
              .carousel-item.active
                %img.d-block.img-thumbnail{src: url_for(image)}  
            -else
              .carousel-item
                %img.d-block.img-thumbnail{src: url_for(image)}
        %a.carousel-control-prev{"href"=>"#carouselExampleControls","role"=>"button","data-slide"=>"prev"}
          %span.carousel-control-prev-icon{"aria-hidden"=>"true"}
          %span.sr-only Previous
        %a.carousel-control-next{"href"=>"#carouselExampleControls","role"=>"button","data-slide"=>"next"}
          %span.carousel-control-next-icon{"aria-hidden"=>"true"}
          %span.sr-only Next

    .col-6
      %h1=@post.title
      %p=@post.comment.html_safe

app/views/posts/create.html.haml
%h1 Post creado exitosamente

app/views/posts/edit.html.haml
.col-sm-12
  %h1 Editar item
.col-10.mt-5
  .card
    .card-body
      = form_with model: @post, multipart: true  do |f|
        .row
          .col-12
            = f.label :Titulo
            = f.text_field :title , class: "form-control"
          .col-12
            = f.label :Comentario
            = f.trix_editor :comment, class: "form-control"
          .col-12
            = f.label :Imagenes
            <input type="file" name="post[images][]" multiple>
          .col-12
            = f.label "fecha"
            = f.date_field :date, class: "form-control" 
          .col-12.mt-3
            = f.submit class: "btn btn-secondary button_color_pink"

app/views/posts/index.html.haml
.container
  .row
    .col-12
      .btn.button_home_color
        = link_to('agregar', new_post_path)
      .card
        .card-header
          Items Galeria
        .card-body
          - @posts.each do |post|  
            .row.mt-3.border-top.p-4
              .col-sm-2
                = post.title
                -# = image_tag url_for(image.image), alt: '', height: '80%', width: '80%', class: 'image_thumbnail'  
              .col-sm-7
                = post.comment.html_safe
              .col-sm-1
                = link_to('Editar', edit_post_path(post))
              .col-sm-1
                = link_to('Eliminar', edit_post_path(post))
              .col-sm-1
                = link_to('eliminar', post_path(post), method: :delete, data: { confirm: 'Estas Seguro?' })


                  

    

app/views/posts/new.html.haml
.col-sm-12
  %h3 Nuevo elemento de Galeria
.col-10
  .card
    .card-body
      = form_with model: @post, multipart: true  do |f|
        .row
          .col-12
            = f.label :Titulo
            = f.text_field :title , class: "form-control"
          .col-12
            = f.label :Categoria
            = f.select(:category_id, Category.all.collect{|d| [d.name,d.id]})
          .col-12
            = f.label :Comentario
            = f.trix_editor :comment, class: "form-control"
          .col-12
            = f.label :Imagenes
            <input type="file" name="post[images][]" multiple>
          .col-12.mt-3
            = f.submit "crear", class: "btn btn-secondary button_color_pink"
.col-12.mt-3
  .card
    .card-header
      Items Galeria
    .card-body
      - @posts.each do |post|  
        .row.mt-3.border-top.p-4
          .col-sm-2
            = post.title
            -# = image_tag url_for(image.image), alt: '', height: '80%', width: '80%', class: 'image_thumbnail'  
          .col-sm-6
            = post.comment
          .col-sm-2
            = link_to('Editar', edit_post_path(post))
          .col-sm-2
            = link_to('Eliminar', edit_post_path(post))
          


              